# Generated by Django 2.2.6 on 2021-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210711_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(upload_to='movie', verbose_name='Картинки'),
        ),
    ]
