# Generated by Django 2.2.6 on 2021-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210711_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
