# Generated by Django 2.2.6 on 2021-07-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210713_0333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieVideo',
        ),
        migrations.AddField(
            model_name='movie',
            name='film',
            field=models.FileField(default=1, upload_to='film'),
            preserve_default=False,
        ),
    ]
