# Generated by Django 2.2.6 on 2021-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210713_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(default=1, upload_to='trailer'),
            preserve_default=False,
        ),
    ]
